### ISSUE TITLE
Error while trying to edit 

### ISSUE THREAD

**Issue by OverwatchJohnson** [thinksquirrel/fluviofx#17]
Hi !

While im trying to edit fluid simulation i have that error in console:

Shader error in '[System 1]E Update': 'max': no matching 3 parameter intrinsic function; Possible intrinsic functions are: max(float|half|double|min10float|min16float|int|uint|min12int|min16int|min16uint, float|half|double|min10float|min16float|int|uint|min12int|min16int|min16uint) at kernel CSMain at System.vfx(76) (on d3d11)

Im not sure what im doing wrong ;)

**Comment by lmontoute** [comment]
Hm, I haven't seen this one. Would it be possible to send over a few things?

- Unity version, SRP version, VFX graph version
- Your editor platform, target platform, graphics API, and graphics device
- A screenshot of the generated code

This will help tremendously in figuring out if it's an issue specific to some hardware or a problem with code generation.

**Comment by OverwatchJohnson** [comment]
Hi !

Information below:
- Graphic device: GeForce GTX1080
- Unity Editor Version: 2018.3.9f1
- Target Platform: PC (Windows)
- VFX Graph version: 4.10.0
- HDRP Version: 4.10.0

Error code:
![error_code](https://user-images.githubusercontent.com/29740883/55309806-215ed480-545f-11e9-9054-32e6b373d4e1.PNG)

**Comment by PeterCsubak** [comment]
Hi @lmontoute !

I've ran into the same problem, and it happens in the `SurfaceNormal` calculation, the line which has the problem, is this:
``` 
    // Write to normal
    float normalLen = max(length(n), FLUVIO_EPSILON);
```

And in the same script the `FLUVIO_EPSILON` is defined like this:
```
#define FLUVIO_EPSILON 9,999999E-11
```

I'm really bad with shaders, but isn't that definition should be `9.999999E-11` with a "dot" instead of a comma? (So it represents a float literal? Or is that means the same thing, with a comma? )

I couldn't manage to test my theory, because unity keeps overriding my changes on the script. (It's not a surprise since it's a generated script :) ) 
So I figured I should modify the `ShaderPostprocessor` but I'm not sure how. Just guessing that this is a localisation bug, because in my regional settings the decimal separator is `,`, but how do you tell it to c# not to use that?

**Comment by PeterCsubak** [comment]
As it turns out that was the problem indeed. So I created a PR with the bugfix.

**Comment by lmontoute** [comment]
Ah, good find! Merged your PR, so this should be solved on the latest master.
