### ISSUE TITLE
Installation problems on 2019.1.8f1

### ISSUE THREAD

**Issue by gpoole** [thinksquirrel/fluviofx#21]
I had a few problems when I originally installed this on 2019.1.8f1 that I think could be documented in the install steps. If these all make sense I'm happy to open a PR to add notes:

* I got errors saying `The type or namespace name 'Timeline' does not exist in the namespace`, which I was able to stop by installing Cinemachine 2.3. Not sure if that's the right fix or if there was a change in 2019 to move Cinemachine out of the main install?
* I also got errors saying `The type or namespace name 'VFX' does not exist in the namespace` because I needed to install VFX graph. As a new user I thought it came with the HDRP project template and didn't realise I needed it as a dependency.
* After everything was installed I found the system wasn't quite working right because the calculate forces node was missing from the graph I created (I added it and everything worked after that):
![Capture](https://user-images.githubusercontent.com/2898433/60556046-c8b31680-9d82-11e9-8c2c-4eb67ec509d6.PNG)

**Comment by lmontoute** [comment]
Hi @gpoole,

Can you give the latest PR a try and see if that fixes your issue? Note the change with installation instructions as well. You may need to remove and reinstall the needed packages in order to get things working.

It should also fix the missing Calculate Forces node in 2019 (once you re-add it, it shouldn't disappear on save).

**Comment by lmontoute** [comment]
Fixed by #23
